### ISSUE TITLE
location.sh

### ISSUE THREAD

**Issue by Amarendra-ai** [suraj-singh12/BashScripts#24]
hey @suraj-singh12 I want to add a bash script which takes ip address and gives location. Please assign this issue to me

**Comment by Amarendra-ai** [comment]
> Sure, just ensure your script is as accurate as possible in finding the location.

Ok

**Comment by sadityakumar9211** [comment]
Hey I want to work on this too. Kindly also assign me this issue.

**Comment by sadityakumar9211** [comment]
Hey, I added a `location.sh` script to find locations based on IP address. But I guess I made a mistake, and that commit was merged with another PR #32 . Can you please tell how do I rectify it? The location.sh script is added [here](https://github.com/suraj-singh12/BashScripts/tree/main/geolocation).
